### PR TITLE
Add overview paragraph

### PR DESCRIPTION
**Pull request by JoanneBogart**
I didn't change the text in home.jinja2 significantly because I see it distinguishes between users who are logged in or not, with useful information in both cases.  It could perhaps be shortened a bit by omitting the suggestion to look below, especially if we use a smaller font so that "below" is not very far.

### CODE REVIEW

**Comment by yymao** [comment]
Ah, I was just working on #37 (PR just opened) to clear up a space in the home page for the overview text. After #37 is merged , the overview text can go to `overview.md` and it will appear side-by-side with "Getting Started".

**Review by yymao — CHANGES_REQUESTED** [review]
Note that the overview text should be moved to `overview.md` once #37 is merged. 

The sentence "Note that the complete dataset is about 180 Gbytes; you may want to start with a subset." is not quite right because now cosmoDC2 also live here.

**Comment by JoanneBogart** [comment]
I've modified the text concerning sizes.
It's not clear to me that putting the two sections side by side is better than having the overview on top.  Most people coming to the page for the first time should read that paragraph first, but it's short enough that people just wanting to look up the details can skip right to them.  What are the advantages of side-by-side?

**Comment by yymao** [comment]
It's just style. Right now this PR would result in a very long left column and a very short right column, which do look very balanced.

The overview text needs some more edits. The cosmoDC2 files are in HDF5. 

Since the overview text will appear on the front page, does it still make sense to refer to specific catalogs?

**Comment by yymao** [comment]
Note that the Getting Started page is not linked from the home page, but directly displayed in the home page.

**Comment by JoanneBogart** [comment]
I know that the old design was to include getting_started.md and it appears your new design includes both overview and getting_started in adjacent columns.   I'm suggesting we stick with the original arrangement: just one column, with the overview paragraph preceding the list.  

Including the CosmoDC2 certainly does complicate things.  Once we merge in some version of the currrent changes under consideration I suspect we ought to rethink the whole organization. Most of the information applies to both, but not all.  Perhaps we need a subsection specific to DC2 data, maybe another specific to CosmoDC2.  It depends on how many places we need to say something different about one or the other.

**Review by yymao — APPROVED** [review]
I'm approving this PR so we can move forward, given the limited time. But IMO we still need to edit the text to make it more general than it currently is.  We can discuss the style in #37.

**Pull request merged**
