### PR TITLE
Update GCRCatalogs installation doc

### PR DESCRIPTION
**Pull request by yymao**
This PR addresses #34

### CODE REVIEW

**Review by JoanneBogart — CHANGES_REQUESTED** [review]
Basically it looks good.  You might consider adding subsections 
`#### Preliminaries`
and
`#### Install`
under each of the conda install and pip install sections.

Also I'm wondering a bit about the conda install instructions.  I had already successfully installed an earlier release with conda and just now installed the new version, also successfully. When I issue
`conda config --show channels` the response is `defaults`
If this is somehow equivalent to `conda-forge` we should say so.

**Comment by yymao** [comment]
That's curios. `defaults` is different from `conda-forge`. But I guess you have installed a non-RC version of `GCRCatalogs` before? If so then yes it would work. The issue is that the dependencies of `GCRCatalogs` live in `conda-forge` but the RCs live in `conda-forge/label/lsstdesc-gcr-catalogs_rc` and hence without adding the `conda-forge` channel conda won't be able to fetch its dependencies. 

If we won't do RCs in the future, I can actually remove the setting channel part of the doc.

**Comment by heather999** [comment]
`defaults` really isn't equivalent to `conda-forge`: https://conda-forge.org/docs/user/tipsandtricks.html  I think it's just generally best to suggest that people use the `conda-forge` channel consistently.

**Comment by yymao** [comment]
I've added the subsubheaders, but left the instructions of adding conda-forge channel there.

**Review by JoanneBogart — APPROVED** [review]
Thanks, @yymao 
Looks good.

**Pull request merged**
