### PR TITLE
Update style.css

### LINKED ISSUE #23: CSS adjustment for title in "Datasets" and "Browse Datasets" pages
Currently the title in "Datasets" and "Browse Datasets" pages look like:

image

image

Some CSS adjustment should be able to fix this formatting issue.

### PR DESCRIPTION
**Pull request by yymao**
This should fix #23 the header display issue. At the same time I also discovered why the bullet points are not working so I fix that in this PR too.

### CODE REVIEW

**Comment by yymao** [comment]
Rebased onto current main branch.

**Comment by heather999** [comment]
I've deployed this to the dev portal, but I don't see the changes either in the bullets appearing or on the Browse Datasets.
I confirmed that that tail of style.css reflects what is in this PR by opening a shell on SPIN:
```
body {
  webkit-tap-highlight-color: #4d75a8;
}

p.task-detail {
  margin: 10px 0;
}
```

**Comment by yymao** [comment]
I do see bullet points on the test site now, and the header issue is also fixed. Do you see the same @heather999 ?

**Comment by heather999** [comment]
Yes, now I do.  Deploying can take a couple of minutes to complete, but in this case, I had to clear my cache locally.  Approving!

**Review by heather999 — APPROVED** [review]
Bullets have appeared the Dataset headings look good

**Pull request merged**
