### PR TITLE
add select/unselect all buttons

### LINKED ISSUE #47: add "Select All" and "UnSelect All" to Browse Data set view
Stephane mentioned this on Slack.  Should be easy enough to implement.

### PR DESCRIPTION
**Pull request by yymao**
Fixes #47. 

I can't test this locally so I am not sure if it actually works. I am opening as a draft PR for now. @heather999  can you push this branch to the test site?

### CODE REVIEW

**Comment by heather999** [comment]
Now deployed to dev.  I see the buttons (maybe they need to be slid over to the right).

**Comment by JoanneBogart** [comment]
This is looking good!  But I still have some nits to pick:
* Text starting "Choose the files.." should be left-adjusted (currently appears to be centered)
* I would revise that text slightly to read 

Choose the files you wish to download, then click the "Transfer" button at the bottom of the page.

or use some other way to make `Transfer` stand out a bit.

**Comment by yymao** [comment]
I've implemented the remaining two items in #1. This PR now fixes #1.

**Comment by heather999** [comment]
deployed to dev portal, but does not seem to be working.  I'm going to clear my cache and try again and then offer more details.

**Comment by heather999** [comment]
Same odd behavior after clearing my cache:
* Clicking `Select Example Subset` results in temporarily selecting the checkboxes, the total download appears as NaN but then the page reloads and the selection is lost.
* Clicking `Select All`, leads directly to transfer
I'll take a look at the routing

**Review by heather999 — APPROVED** [review]
Looks ready to go

**Pull request merged**
