### PR TITLE
Update GCRCatalogs installation instructions to use stable v1.2.0

### LINKED ISSUE #42: Update GCRCatalogs installation instructions to use stable v1.2.0
`GCRCatalogs` [v1.2.0](https://github.com/LSSTDESC/gcr-catalogs/releases/tag/v1.2.0) has be released and uploaded to conda-forge. We should update our [instructions](https://github.com/LSSTDESC/desc-data-portal/blob/main/web/portal/templates/doc/install_gcr.md). 

I can work on this when @JoanneBogart finished the update on #38.

### PR DESCRIPTION
**Pull request by yymao**
Fixes #42

I actually decide to remove the conda-forge channel instructions because on my machine, where I used miniforge and has conda-forge already, the instructions actually added default channel for me, which is not great.. 

If anyone has insight that's welcome. But for now I believe adding `-c conda-forge` to `conda install` would work in both cases.

### CODE REVIEW

**Review by JoanneBogart — APPROVED** [review]
This looks fine to me, but I know nothing about the conda-forge channel issue.  Perhaps wait to see if @heather999 has any ideas?

**Comment by heather999** [comment]
I guess I'm wondering if we could at least include a link to [conda-forge's doc that discusses this.](https://conda-forge.org/docs/user/tipsandtricks.html).  I think it's fine to tell people to explicitly install and include the `-c conda-forge` flag, but if this is an environment they update with other packages - having `defaults` be the priority channel may cause problems down the road for some.

**Comment by yymao** [comment]
OK, I've added a brief note. @heather999 see if that looks good? If so, please go ahead and merge this.

**Review by heather999 — APPROVED** [review]
LGTM

**Pull request merged**
