### PR TITLE
Add cosmoDC2 documentation

### LINKED ISSUE #6: Document CosmoDC2
* Add link to CosmoDC2 papge
* Replicate as appropriate the content of https://portal.nersc.gov/project/lsst/cosmoDC2/_README.html

### PR DESCRIPTION
**Pull request by yymao**
This PR adds cosmoDC2 documentation. The content is mostly copied from https://portal.nersc.gov/project/lsst/cosmoDC2/_README.html but with updated instrcutions or links to existing instructions in the repo. 

Fixes #6

### CODE REVIEW

**Comment by heather999** [comment]
About those README files - I'm assuming these copies from the old portal should be removed from the globus endpoint area?
```
/global/cfs/cdirs/lsst/gsharing/lsstdesc-public/dc2/cosmoDC2_v1.1.4/_README.html
/global/cfs/cdirs/lsst/gsharing/lsstdesc-public/dc2/cosmoDC2_v1.1.4/_README.md
```

**Comment by yymao** [comment]
Yes. These two are the files to be removed.

**Comment by heather999** [comment]
Ok - those are now removed.  Now pushed to the dev portal: http://lb.desc-web-dev.production.svc.spin.nersc.org/
LGTM

**Review by heather999 — APPROVED** [review]
Looks good in the dev portal

**Comment by yymao** [comment]
Thanks, Heather!

**Pull request merged**
